### ISSUE TITLE
Salt on Clojars?

### ISSUE THREAD

**Issue by arnaudbos** [Viasat/salt#4]
Hi, thank you for releasing this publicly.

I can't seem to find salt on Clojars or Maven central. Is there a plan to deploy it?

**Comment by david-mcneil** [comment]
I would like to publish to those place, just have not done it yet.

**Comment by arnaudbos** [comment]
Understood, thanks.

**Comment by david-mcneil** [comment]
I deployed to Clojars: https://clojars.org/org.clojars.david-mcneil/salt
